Добавляет сортировку
htmlacademy-react/174891-six-cities-9 pull request #9
Opened 2022-03-29 15:39 UTC by MariaSarbaj

2022-03-29 19:45 UTC, ant1quar requested changes

2022-03-29 19:45 UTC, ant1quar commented on project/src/components/home-page-content/home-page-content.tsx
> +      }
Это лишнее - возвращай 1 или -1.
поменять одинаковые элементы местами можно - результат один и тот же

2022-03-29 19:45 UTC, ant1quar commented on project/src/components/sorting-menu/sorting-menu.tsx
> +  };
вынести в константы

2022-03-29 19:45 UTC, ant1quar commented on project/src/components/sorting-menu/sorting-menu.tsx
> +const getTextBySortingType = (type: OffersSortingType) => {
объявлять тут функцию не очень хорошая идея. надо для такого завести или utils.js файл, или поместить в компоненту

2022-03-29 19:45 UTC, ant1quar commented on project/src/store/reducers/reviews-reducer.ts
> +      return state;
необязательно возвращать стейт

2022-03-30 05:26 UTC, MariaSarbaj commented on project/src/store/reducers/reviews-reducer.ts
> +      return state;
Тогда WebStorm начинает ругаться:(

2022-03-30 08:27 UTC, merged